version: '3.8'

services:
  quote-management:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./quotes.js:/usr/share/nginx/html/quotes.js
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped